### ISSUE TITLE
error on startup

### ISSUE THREAD

**Issue by nicon-dev** [sitrakary/hapi-auto-route#3]
I just tried out the example and got this error:

`server.connection({ port: 3000, labels: ['web'] });
       ^
TypeError: server.connection is not a function
`

is this plugin not compartible to the new hapi v17?

**Comment by sitrakary** [comment]
Hi! Actually this plugins is incompatible with hapi v17.

**Comment by sitrakary** [comment]
Just release [v2.0.0](https://github.com/sitrakary/hapi-auto-route) which is compatible with Hapi v17.x.x
