### ISSUE TITLE
Support for ECMAScript Modules?

### ISSUE THREAD

**Issue by mellisdesigns** [sitrakary/hapi-auto-route#7]
Thoughts on supports ECMAScript modules?

Using dynamic import?

**Comment by sitrakary** [comment]
Currently, We want to supports node v8.9.0 and later, which is the minimum version of node supported by hapi. On the other hand, ES6 module stills experimental on these node version.

**Comment by sitrakary** [comment]
I'll accept PR for these but we need to supports the minimum version of node supported by hapi.
